/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,ts,js}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['"DM Sans"', 'Inter', '-apple-system', '"PingFang SC"', '"Microsoft YaHei"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'Menlo', 'Monaco', 'monospace'],
      },
      colors: {
        brand: {
          coral: '#ff5530',
          magenta: '#ea5ec1',
          blue: '#1456f0',
          'blue-mid': '#3b82f6',
          'blue-deep': '#1d4ed8',
          'blue-700': '#17437d',
          cyan: '#3daeff',
          'blue-200': '#bfdbfe',
          purple: '#a855f7',
          orange: '#f97316',
        },
        canvas: '#ffffff',
        surface: '#f7f8fa',
        'surface-soft': '#f2f3f5',
        hairline: '#e5e7eb',
        'hairline-soft': '#eaecf0',
        ink: '#0a0a0a',
        'ink-strong': '#000000',
        charcoal: '#222222',
        slate: '#45515e',
        steel: '#5f5f5f',
        stone: '#8e8e93',
        muted: '#a8aab2',
        success: { bg: '#e8ffea', text: '#1ba673' },
      },
      borderRadius: {
        xs: '4px', sm: '6px', md: '8px', lg: '12px',
        xl: '16px', xxl: '20px', xxxl: '24px', hero: '32px',
      },
      fontSize: {
        hero: ['80px', { lineHeight: '1.10', letterSpacing: '-2px', fontWeight: '600' }],
        'display-lg': ['56px', { lineHeight: '1.10', letterSpacing: '-1.5px', fontWeight: '600' }],
        'heading-lg': ['40px', { lineHeight: '1.20', letterSpacing: '-1px', fontWeight: '600' }],
        'heading-md': ['32px', { lineHeight: '1.25', letterSpacing: '-0.5px', fontWeight: '600' }],
        'heading-sm': ['24px', { lineHeight: '1.30', fontWeight: '600' }],
        'card-title': ['20px', { lineHeight: '1.40', fontWeight: '600' }],
        subtitle: ['18px', { lineHeight: '1.50', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.50', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.50', fontWeight: '400' }],
        caption: ['13px', { lineHeight: '1.70', fontWeight: '400' }],
        micro: ['12px', { lineHeight: '1.50', fontWeight: '400' }],
      },
      boxShadow: {
        card: '0 0 0 1px rgba(0,0,0,0.04)',
        elevated: '0 4px 6px rgba(0,0,0,0.08)',
        modal: '0 12px 16px -4px rgba(36,36,36,0.08)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
